language: objective-c
podfile: Podfile
before_install:
    - gem install xcpretty
script:
    - set -o pipefail
    - xcodebuild -workspace SwiftWeatherApp.xcworkspace -scheme SwiftWeatherApp test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
